# Generated by Django 3.2.5 on 2021-07-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='occupation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
