# Generated by Django 3.2.5 on 2021-08-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210803_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
