# Generated by Django 3.2.5 on 2021-08-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_post_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
